USE music;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    last_name VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    is_admin BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS artists (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS albums (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR (512) NOT NULL,
    artist_id INT NOT NULL,
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    release_date TIMESTAMP,

    FOREIGN KEY (artist_id)
        REFERENCES artists(id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS tracks (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(512) NOT NULL,
    album_id INTEGER NOT NULL,
    duration TIME NOT NULL,

    FOREIGN KEY (album_id)
        REFERENCES albums(id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS tracks_to_artists (
    track_id INTEGER NOT NULL,
    artist_id INTEGER NOT NULL,

    FOREIGN KEY (track_id)
        REFERENCES tracks(id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    FOREIGN KEY (artist_id)
        REFERENCES artists(id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);
